base_images:
  os:
    name: centos
    namespace: openshift
    tag: "7"
binary_build_commands: make driver
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.18
promotion:
  name: "4.11"
  namespace: ocp
releases:
  initial:
    integration:
      name: "4.11"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.11"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-aws
  steps:
    cluster_profile: aws
    workflow: openshift-e2e-aws
- as: unit
  commands: make test
  container:
    from: src
- as: verify
  commands: make verify
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: openshift
  repo: ibm-powervs-block-csi-driver
